services:
  - type: web
    name: stx-html-example
    runtime: docker
    repo: https://github.com/nicolasguelfi/stx-html-example
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: STX_PASSWORD
        value: changeme
    healthCheckPath: /_stcore/health
